#=================================================
# Description: Build Android HAL and dhd packages using GitHub Actions
# Lisence: MIT
# Author: 0312birdzhang
#=================================================

name: Build SailfishOS dhd
on:
  release:
    types: [published]
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_example:
        description: "example"
        required: true
        default: "hkdm"
#on: 
#  release:
#   types: [published]
#  push:
#    branches: 
#      - master

jobs:

  build:
    runs-on: ubuntu-20.04

    env:
      DEVICE: vince
      VENDOR: xiaomi
      ANDROID_ROOT: /home/runner/work/ci/ci/hadk_14.1/
      SAILFISH_SDK_VERSION: 5.0.0.21

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 20480
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-android: 'true'
        remove-docker-images: 'true'

    - name: Checkout
      uses: actions/checkout@master
        
    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        openjdk-8-jdk android-tools-adb bc bison \
        build-essential curl flex g++-multilib gcc-multilib gnupg gperf \
        imagemagick lib32ncurses-dev \
        lib32readline-dev lib32z1-dev  liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
        libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev \
        qemu-user-static qemu-system-arm e2fsprogs simg2img \
        libtinfo5 libncurses5 gzip virtualenv git python2


    - name: Download repo bin file
      run: |
        mkdir -p ~/bin
        wget 'https://storage.googleapis.com/git-repo-downloads/repo' -P ~/bin
        chmod +x ~/bin/repo
        git config --global user.name "BirdZhang"
        git config --global user.email "0312birdzhang@gmail.com"

    - name: Downloading source code
      run: |
        source hadk.env
        mkdir -p $ANDROID_ROOT
        cd $ANDROID_ROOT
        repo init -u https://github.com/mer-hybris/android.git -b hybris-14.1 --depth=1
        repo sync -j8 -c --no-clone-bundle --no-tags
    
    - name: Clone device spec source
      run: |
        source hadk.env
        git clone https://github.com/Sailfish-On-Vince/device_xiaomi_vince.git $ANDROID_ROOT/device/xiaomi/vince --depth=1 
        git clone https://github.com/Sailfish-On-Vince/vendor_xiaomi_vince.git $ANDROID_ROOT/vendor/xiaomi/vince --depth=1
        git clone https://github.com/Sailfish-On-Vince/Xiaomi_Kernel_OpenSource.git $ANDROID_ROOT/kernel/xiaomi/msm8953 --depth=1
        rm -rf $ANDROID_ROOT/hybris/hybris-boot
        git clone https://github.com/Sailfish-On-Vince/hybris-boot.git $ANDROID_ROOT/hybris/hybris-boot
        git clone --recurse-submodules https://github.com/Sailfish-On-Vince/droid-hal-vince.git $ANDROID_ROOT/rpm 
        git clone --recurse-submodules https://github.com/Sailfish-On-Vince/droid-config-vince.git $ANDROID_ROOT/hybris/droid-configs
        git clone --recurse-submodules https://github.com/Sailfish-On-Vince/droid-hal-version-vince.git $ANDROID_ROOT/hybris/droid-hal-version-vince
        rm -rf $ANDROID_ROOT/external/droidmedia
        git clone https://github.com/sailfishos/droidmedia.git $ANDROID_ROOT/external/droidmedia

    - name: Build HAL
      run: |
        chmod +x build-hal.sh
        sudo ln -sf /usr/bin/python2.7 /usr/bin/python
        bash build-hal.sh
      shell: bash

    - name: Build dhd in container
      run: |
        echo "clean more folders"
        rm -rf $ANDROID_ROOT/prebuilts $ANDROID_ROOT/external/chromium* $ANDROID_ROOT/tools $ANDROID_ROOT/packages
        rm -rf $ANDROID_ROOT/out/build-lineage_vince.ninja
        chmod +x build-rpm.sh
        sudo docker pull coderus/sailfishos-platform-sdk:$SAILFISH_SDK_VERSION
        sudo docker run -v /home/runner/work:/home/mersdk/work coderus/sailfishos-platform-sdk:$SAILFISH_SDK_VERSION /bin/sh /home/mersdk/work/ci/ci/build-rpm.sh
      shell: bash

    - name: Check free disk
      if: failure()
      run: |
        df -h
      shell: bash

    - name : Upload boot image
      uses: actions/upload-artifact@master
      with:
        name: hybris-boot.img.zip
        path: ${{env.ANDROID_ROOT}}/out/target/product/${{env.DEVICE}}/hybris-boot.img

    - name : Upload droid-local-repo
      uses: actions/upload-artifact@master
      with:
        name: droid-local-repo.zip
        path: ${{env.ANDROID_ROOT}}/droid-local-repo
